global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['phoenix_node_exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['phoenix_postgres_exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['phoenix_redis_exporter:9121']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['phoenix_cadvisor:8080']
