# Grafana Datasources for Phoenix
apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1

  # PostgreSQL for direct database queries
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: phoenix_postgres:5432
    database: phoenix_core
    user: phoenix
    secureJsonData:
      password: PhoenixDB_2025_Secure!
    jsonData:
      sslmode: disable
      postgresVersion: 1600  # PostgreSQL 16
      timescaledb: false
    editable: true
    version: 1
