global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'saccharomyces'

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_db:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_cache:9121']

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n_automation:5678']
        metrics_path: '/metrics'
